manifest:
  remotes:
    - name: ncs
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      remote: ncs
      path: ncs
      revision: v2.6.0
      import: true
  self:
    path: modules/lib/test-company-sdk